### ISSUE TITLE
Would Unist make a good programming language AST format?

### ISSUE THREAD

**Issue by anko** [syntax-tree/unist#10]
Hi again @wooorm (and other AST enthusiasts),

I develop an experimental programming language called [eslisp](https://github.com/anko/eslisp), which is basically a JavaScript syntax optimised for code-modifying macros that let users add language features. It might be helpful to think of it as a programming language processing tool.

Eslisp's current AST representation contains exactly the same information as Unist, right down to location data, but [currently organised differently](https://github.com/anko/sexpr-plus#readme). I was writing my own tools for reading and modifying it, then realised I'm basically duplicating [Unist utilities](https://github.com/syntax-tree/unist#unist-utilities).

I thought I'd open a dialogue before I start "hammering on screws" and making it a dependency. Have you considered _programming_ languages as a Unist use-case? Is this a sane thing to be doing, long-term?

**Comment by wooorm** [comment]
Hi again! 👋

Whether Unist works for programming languages? I think so, yes.

I haven’t really investigated that, but I know @JDvorak is working on [recode](https://github.com/JDvorak/recode), which is remark/retext/rehype for JavaScript. I think that’s very early stages though?

> I thought I'd open a dialogue

Yes!

> before I start "hammering on screws"

Like what? What are the things you’re considering? What downsides do you see? What alternatives are there?

**Comment by JDvorak** [comment]
Hell yeah!

@wooorm's basic structure is totally applicable to programming languages. It is just a super verbose data structure for relating nodes and their children explicitly, and _consistently_ (I'm looking at you estree). Because of its readability and programmatic properties, I try to make my user-facing trees Unist shaped where possible so that I can rely on the existing tree toolchain, and build upon it. While, interiorly, I might actually build temporary tree structures that have certain performance characteristics. Like, for instance, my fledgling [quasi tree adjoining grammar](https://github.com/JDvorak/mapcast) parser is currently written in an alien tree-tongue, but in subsequent revisions will have a Unist format to organize dependencies amongst transforms and enable userland to better use the tool. Unfortunately, I am not a great open source contributor since I cannot put aside time until next month to return to working on it, and even then, only weekend. ;-; **but this is all irrelevant to you, @anko **, the big take away is that yes, it is totally fine for anything tree shaped, just make sure you are working on tree shaped things, because all the tools fall over if a single cycle is introduced.

**Comment by anko** [comment]
> Whether Unist works for programming languages? I think so, yes.

:+1::sparkles:

> What are the things you’re considering? What downsides do you see?

Everything around Unist is currently natural-language-related, so I thought I'd probe for unspoken assumptions just in case. I've read around and see no technical problems.

> What alternatives are there?

None I know, except my ad-hoc format.

> [recode](https://github.com/JDvorak/recode)

Cool! I'll be following.

Quick comparison regarding our uses of Unist: Recode invents a new Unist-compatible AST format for JavaScript, on the same level as [ESTree](https://github.com/estree/estree) (which I currently use for JS ASTs, because [the current JavaScript-modifying tools ecosystem targets it](https://github.com/estools)). I'm considering Unist for an [S-expression](https://en.wikipedia.org/wiki/S-expression) representation, for processing before it's translated to JavaScript.

- - -

I'll try it and report back.
